/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.salaodebeleza.view;

import com.mycompany.salaodebeleza.model.Equipamento;
import com.mycompany.salaodebeleza.controller.GerenciaEquipamento;
import com.mycompany.salaodebeleza.controller.GerenciaPessoa;
import com.mycompany.salaodebeleza.controller.GerenciaProduto;
import com.mycompany.salaodebeleza.controller.GerenciaTipoServico;
import com.mycompany.salaodebeleza.model.Pessoa;
import com.mycompany.salaodebeleza.model.Produto;
import com.mycompany.salaodebeleza.model.TipoServico;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sarah
 */
public class Principal extends javax.swing.JFrame {
    private ArrayList<Pessoa> pessoas;
    private ArrayList<Equipamento> equipamentos;
    private ArrayList<TipoServico> tiposServico;
    private ArrayList<Produto> produtos;
    private GerenciaPessoa gerenciaPessoa;
    private GerenciaEquipamento gerenciaEquipamento;
    private GerenciaTipoServico gerenciaTipoServico;
    private GerenciaProduto gerenciaProduto;
    
    public Principal() {
        initComponents();
        pessoas = new ArrayList<>();
        equipamentos = new ArrayList<>();
        tiposServico = new ArrayList<>();
        produtos = new ArrayList<>();
        gerenciaPessoa = new GerenciaPessoa(pessoas);
        gerenciaEquipamento = new GerenciaEquipamento(equipamentos);
        gerenciaTipoServico = new GerenciaTipoServico(tiposServico);
        gerenciaProduto = new GerenciaProduto(produtos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemCadCliente = new javax.swing.JMenuItem();
        itemCadFuncionario = new javax.swing.JMenuItem();
        itemCadAgendamento = new javax.swing.JMenuItem();
        itemCadVenda = new javax.swing.JMenuItem();
        itemCadEquipamento = new javax.swing.JMenuItem();
        itemCadServico = new javax.swing.JMenuItem();
        itemCadProduto = new javax.swing.JMenuItem();
        menuEdicao = new javax.swing.JMenu();
        itemEdCliente = new javax.swing.JMenuItem();
        itemEdFuncionario = new javax.swing.JMenuItem();
        itemEdAgendamento = new javax.swing.JMenuItem();
        itemEdVenda = new javax.swing.JMenuItem();
        itemEdEquipamento = new javax.swing.JMenuItem();
        itemEdServico = new javax.swing.JMenuItem();
        itemEdProduto = new javax.swing.JMenuItem();
        menuExclusao = new javax.swing.JMenu();
        itemExCliente = new javax.swing.JMenuItem();
        itemExFuncionario = new javax.swing.JMenuItem();
        itemExAgendamento = new javax.swing.JMenuItem();
        itemExVenda = new javax.swing.JMenuItem();
        itemExEquipamento = new javax.swing.JMenuItem();
        itemExServico = new javax.swing.JMenuItem();
        itemExProduto = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        itemConCliente = new javax.swing.JMenuItem();
        itemConFuncionario = new javax.swing.JMenuItem();
        itemConAgendamento = new javax.swing.JMenuItem();
        itemConVenda = new javax.swing.JMenuItem();
        itemConEquipamento = new javax.swing.JMenuItem();
        itemConServico = new javax.swing.JMenuItem();
        itemConProduto = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemReCliente = new javax.swing.JMenuItem();
        itemReFuncionario = new javax.swing.JMenuItem();
        itemReAgendamento = new javax.swing.JMenuItem();
        itemReVenda = new javax.swing.JMenuItem();
        itemReEquipamento = new javax.swing.JMenuItem();
        itemReServico = new javax.swing.JMenuItem();
        itemReProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        itemCadCliente.setText("Cliente");
        itemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadCliente);

        itemCadFuncionario.setText("Funcionário");
        itemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadFuncionario);

        itemCadAgendamento.setText("Agendamento");
        menuCadastro.add(itemCadAgendamento);

        itemCadVenda.setText("Venda");
        menuCadastro.add(itemCadVenda);

        itemCadEquipamento.setText("Equipamento");
        itemCadEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadEquipamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadEquipamento);

        itemCadServico.setText("Tipo de serviço");
        itemCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadServicoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadServico);

        itemCadProduto.setText("Produto");
        itemCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadProduto);

        menuBar.add(menuCadastro);

        menuEdicao.setText("Edição");
        menuEdicao.setToolTipText("");

        itemEdCliente.setText("Cliente");
        menuEdicao.add(itemEdCliente);

        itemEdFuncionario.setText("Funcionário");
        menuEdicao.add(itemEdFuncionario);

        itemEdAgendamento.setText("Agendamento");
        menuEdicao.add(itemEdAgendamento);

        itemEdVenda.setText("Venda");
        menuEdicao.add(itemEdVenda);

        itemEdEquipamento.setText("Equipamento");
        menuEdicao.add(itemEdEquipamento);

        itemEdServico.setText("Tipo de serviço");
        menuEdicao.add(itemEdServico);

        itemEdProduto.setText("Produto");
        menuEdicao.add(itemEdProduto);

        menuBar.add(menuEdicao);

        menuExclusao.setText("Exclusão");

        itemExCliente.setText("Cliente");
        menuExclusao.add(itemExCliente);

        itemExFuncionario.setText("Funcionário");
        menuExclusao.add(itemExFuncionario);

        itemExAgendamento.setText("Agendamento");
        menuExclusao.add(itemExAgendamento);

        itemExVenda.setText("Venda");
        menuExclusao.add(itemExVenda);

        itemExEquipamento.setText("Equipamento");
        menuExclusao.add(itemExEquipamento);

        itemExServico.setText("Tipo de serviço");
        menuExclusao.add(itemExServico);

        itemExProduto.setText("Produto");
        menuExclusao.add(itemExProduto);

        menuBar.add(menuExclusao);

        menuConsulta.setText("Consulta");

        itemConCliente.setText("Cliente");
        menuConsulta.add(itemConCliente);

        itemConFuncionario.setText("Funcionário");
        menuConsulta.add(itemConFuncionario);

        itemConAgendamento.setText("Agendamento");
        menuConsulta.add(itemConAgendamento);

        itemConVenda.setText("Venda");
        menuConsulta.add(itemConVenda);

        itemConEquipamento.setText("Equipamento");
        menuConsulta.add(itemConEquipamento);

        itemConServico.setText("Tipo de serviço");
        menuConsulta.add(itemConServico);

        itemConProduto.setText("Produto");
        menuConsulta.add(itemConProduto);

        menuBar.add(menuConsulta);

        menuRelatorio.setText("Relatório");

        itemReCliente.setText("Cliente");
        menuRelatorio.add(itemReCliente);

        itemReFuncionario.setText("Funcionário");
        menuRelatorio.add(itemReFuncionario);

        itemReAgendamento.setText("Agendamento");
        menuRelatorio.add(itemReAgendamento);

        itemReVenda.setText("Venda");
        menuRelatorio.add(itemReVenda);

        itemReEquipamento.setText("Equipamento");
        menuRelatorio.add(itemReEquipamento);

        itemReServico.setText("Tipo de serviço");
        menuRelatorio.add(itemReServico);

        itemReProduto.setText("Produto");
        menuRelatorio.add(itemReProduto);

        menuBar.add(menuRelatorio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadClienteActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente(gerenciaPessoa);
        desktopPane.add(telaCadastroCliente);
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_itemCadClienteActionPerformed

    private void itemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadFuncionarioActionPerformed
        TelaCadastroFuncionario telaCadastroFuncionario = new TelaCadastroFuncionario(gerenciaPessoa);
        desktopPane.add(telaCadastroFuncionario);
        telaCadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_itemCadFuncionarioActionPerformed

    private void itemCadEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadEquipamentoActionPerformed
        if(!gerenciaPessoa.temFuncionario()){
            JOptionPane.showMessageDialog(this, "Cadastre um funcionário antes!");
            return;
        }
        
        TelaCadastroEquipamento telaCadastroEquipamento = new TelaCadastroEquipamento(gerenciaEquipamento, gerenciaPessoa);
        desktopPane.add(telaCadastroEquipamento);
        telaCadastroEquipamento.setVisible(true);
    }//GEN-LAST:event_itemCadEquipamentoActionPerformed

    private void itemCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadServicoActionPerformed
        TelaCadastroTipoServico telaCadastroTipoServico = new TelaCadastroTipoServico(gerenciaTipoServico);
        desktopPane.add(telaCadastroTipoServico);
        telaCadastroTipoServico.setVisible(true);
    }//GEN-LAST:event_itemCadServicoActionPerformed

    private void itemCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadProdutoActionPerformed
        TelaCadastroProduto telaCadastroProduto = new TelaCadastroProduto(gerenciaProduto);
        desktopPane.add(telaCadastroProduto);
        telaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_itemCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemCadAgendamento;
    private javax.swing.JMenuItem itemCadCliente;
    private javax.swing.JMenuItem itemCadEquipamento;
    private javax.swing.JMenuItem itemCadFuncionario;
    private javax.swing.JMenuItem itemCadProduto;
    private javax.swing.JMenuItem itemCadServico;
    private javax.swing.JMenuItem itemCadVenda;
    private javax.swing.JMenuItem itemConAgendamento;
    private javax.swing.JMenuItem itemConCliente;
    private javax.swing.JMenuItem itemConEquipamento;
    private javax.swing.JMenuItem itemConFuncionario;
    private javax.swing.JMenuItem itemConProduto;
    private javax.swing.JMenuItem itemConServico;
    private javax.swing.JMenuItem itemConVenda;
    private javax.swing.JMenuItem itemEdAgendamento;
    private javax.swing.JMenuItem itemEdCliente;
    private javax.swing.JMenuItem itemEdEquipamento;
    private javax.swing.JMenuItem itemEdFuncionario;
    private javax.swing.JMenuItem itemEdProduto;
    private javax.swing.JMenuItem itemEdServico;
    private javax.swing.JMenuItem itemEdVenda;
    private javax.swing.JMenuItem itemExAgendamento;
    private javax.swing.JMenuItem itemExCliente;
    private javax.swing.JMenuItem itemExEquipamento;
    private javax.swing.JMenuItem itemExFuncionario;
    private javax.swing.JMenuItem itemExProduto;
    private javax.swing.JMenuItem itemExServico;
    private javax.swing.JMenuItem itemExVenda;
    private javax.swing.JMenuItem itemReAgendamento;
    private javax.swing.JMenuItem itemReCliente;
    private javax.swing.JMenuItem itemReEquipamento;
    private javax.swing.JMenuItem itemReFuncionario;
    private javax.swing.JMenuItem itemReProduto;
    private javax.swing.JMenuItem itemReServico;
    private javax.swing.JMenuItem itemReVenda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuEdicao;
    private javax.swing.JMenu menuExclusao;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
